### ISSUE TITLE
// from  与  //to 构造 SipURI 都使用 设备deviceId问题 

### ISSUE THREAD

**Issue by angelshowzhe** [xiongziliang/ZLMediaKit#294]
是这样的,今天调试视频直播接口为 /api/play/{deviceId}/{channelId}  在
 invite,createInviteRequest(SIPRequestHeaderProvider.java line 74) //from 与 //to  构造SipURI 时候 因为都采用了device.getDeviceId() 也就是设备id导致 视频不能播放 ,后来 我在//to的地方 传递 channelId ,可以播放摄像头视频了 但是 报了一个
 javax.sip.SipException: Cannot create ACK - no remote Target!
	at gov.nist.javax.sip.stack.SIPDialog.createAck(SIPDialog.java:3122)
	at com.genersoft.iot.vmp.gb28181.transmit.response.impl.InviteResponseProcessor.process(InviteResponseProcessor.java:33)
	at com.genersoft.iot.vmp.gb28181.SipLayer.processResponse(SipLayer.java:129)
	at gov.nist.javax.sip.EventScanner.deliverResponseEvent(EventScanner.java:317)
	at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:148)
	at gov.nist.javax.sip.EventScanner.run(EventScanner.java:513)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xiongziliang** [comment]
你issue提交错了地方吧？你去这个项目提交吧：https://github.com/swwheihei/wvp

**Comment by angelshowzhe** [comment]
> 你issue提交错了地方吧？你去这个项目提交吧：https://github.com/swwheihei/wvp

抱歉,不好意思...
